name: ggomruk_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dart_code_metrics: ^5.7.6
  go_router: ^14.2.7
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.1
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  logger: ^2.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/